export const portfolioInfo = [
	"Paolo Secci is an AI Systems Engineer, Cloud-Native & Full-Stack Architect born, raised, and based in Los Angeles, California. He specializes in AI/ML systems, cloud infrastructure, data engineering, and full-stack development.",
	"Experience: LLM Data Scientist at Turing in Palo Alto, California (April 2024 - April 2025): Post-trained a frontier LLM in tool-augmented, multi-step reasoning, and code generation workflows; Applied SFT to diagnose and correct tool routing errors, code execution faults, and hallucinations; Engineered structured training datasets for advanced Python visualization across multiple libraries.",
	"Experience: Flight Software Engineer at PoliSpace in Milan, Italy (May 2021 - April 2024): Core Flight Software Engineer for 6S CubeSat mission in collaboration with ESA via FYS Program; Developed Telemetry and AOCS Interfaces in Embedded C with strict time and memory constraints; Won the LeanSpace Hackathon at the Space Tech Expo 2022 in Bremen, Germany.",
	"Experience: Software Development Intern at Gucci in Milan, Italy (Octover 2019 - September 2020): Agile team “Zero” member tasked with the DevOps processes of Gucci’s SAP system for e-commerce; Implemented gucci.com's “Contact Us” page in React and Java and tested features extensively in QA.",
	"Education: BS in Engineering of Computing Systems from Politecnico di Milano. Data Analytics Bootcamp Certificate from USC Viterbi School of Engineering. High School Diploma from Loyola High School of Los Angeles.",
	"Tech Skills: Programming Languages - Python, C, Java, TypeScript, JavaScript, Bash, VHDL; Application Layer - Next.js, React, Node.js, FastAPI, Vercel; AI & ML Systems - LLM Post-Training, PyTorch, TensorFlow, Keras, Spark, Pandas, LangChain; Data & Storage - MySQL, PostgreSQL, MongoDB, Redis; Cloud & Infrastructure - GCP, AWS, Azure, Kubernetes, Terraform, Docker, Serverless, CI/CD, Linux",
	"Product: Virgil - a production-grade RAG-based AI assistant for PDF ingestion and contextual querying. Deployed on Vercel and built with serverless full-stack architecture using Next.js (App Router), Prisma ORM, PostgreSQL (Neon), and OpenAI embeddings, my app features both voice and text interaction, TailwindCSS styling, and scalable infrastructure.",
	"Product: Le Swish Prophet - a web application designed to predict the outcomes of NBA games and outperform Las Vegas sportsbooks. The predictive algorithm uses a dynamically trained ML model, the data mining software uses a robust ETL system, and the site runs on serverless architecture on Cloud Run in the Google Cloud.",
	"Languages: English (native), Spanish (fluent), Italian (fluent).",
	"Contact: Email paolosecci98@gmail.com , LinkedIn linkedin.com/in/paolodanilosecci , GitHub github.com/paolosecci .",
	"Personality: Surfing, Philosophy, and Tacos! - or - Romanticism Era Art and Roman Empire History!"
];
